version: '3'
services:
  recipe-book-api:
    build:
      context: ./api
    ports:
      - "3080:3080"
    container_name: recipe-book-api
    volumes:
       - ./api:/usr/src/app/api
       - /usr/src/app/api/node_modules

  recipe-book-ui:
    build:
      context: ./ui
    ports:
      - "3000:3000"
    container_name: recipe-book-ui
    stdin_open: true
    volumes:
       - ./ui:/usr/src/app/ui
       - /usr/src/app/ui/node_modules

  recipe-book-postgres:
    container_name: recipe-book-postgres
    image: 'postgres:14.3-alpine'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=recipes
    volumes:
      - ./database-scripts:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
