name: Tech Test

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install all dependencies
      run:
        npm run postinstall

    - name: Install root project's dependencies
      run:
        npm install

    - name: Run ESLint on backend
      run: npm run lint-be

    - name: Run ESLint on frontend
      run: npm run lint-fe

    #- name: Run tests
    #  run: |
    #    npm test
